export const cuisineList = [
  "North Indian",
  "Italian",
  "Punjabi",
  "Chinese",
  "Rajasthani",
  "Mexican",
  "Bengali",
  "Japanese",
  "Maharashtrian",
  "Thai",
  "South Indian",
  "Greek",
  "Goan",
  "American",
  "Andhra",
  "Korean",
  "Bihari",
  "French",
  "Kerala",
  "Vegan",
  "Spanish",
  "Mediterranean",
  "Desserts",
  "Tacos",
  "BBQ",
  "Sushi",
  "Bakery",
  "Cafe",
   "Mughlai",
   "Indian",
   "Tandoori",
   "Hyderabadi",
   "Healthy",
          "Vegetarian",
          "Street Food",
          "Biryani",
          "Salads",
          "Cafe",
          "Mediterranean",
]